### PR TITLE
Feat/submit website

### PR DESCRIPTION
**Pull request by Ian-Bright**
Resolves: 
https://github.com/State-Channel-4/frontend/issues/25
https://github.com/State-Channel-4/frontend/issues/33

Redesign of the submit website page. User can input a site url, description (title), and tags before submitting a video. Users also have the ability to add new tags through this page

### CODE REVIEW

**Comment by Ian-Bright** [comment]
Two things have come to mind:

1. Think it needs to be made more obvious that the slider is disabled when proper inputs have not been provided
2. The description (title) seems like something we should require or have some default value provided if nothing is typed in

**Comment by thebeyondr** [comment]
> Think it needs to be made more obvious that the slider is disabled when proper inputs have not been provided

I'd prefer to show good error messages under the relevant input element than disabling the button

> The description (title) seems like something we should require or have some default value provided if nothing is typed in

Agreed, we should require this. I don't think we should provide a default value though

@ChialiT please weigh in on these^^

### Some requests before approval:
- Make the preview trigger after the focus is removed from the input (onBlur)
- The label text size seems too big

----
👏🏽 **Great stuff so far, glad to see this transformed from design to usable UI!**

**Comment by Ian-Bright** [comment]
Took care of those items we discussed and your requests before merging @thebeyondr

**Comment by thebeyondr** [comment]
@Ian-Bright looks good, discovered a few things
1. I can trigger the url send mid while a tag is being created (pic related)
2. The sign in link in the nav menu didn't seem to be working
3. When I'm not signed in and attempt to sign in with Google the page doesn't reload. I don't have an account so it should be a sign-up operation instead of a sign-in one

image

**Comment by Ian-Bright** [comment]
Ok disabled the slider when creating a tag. The sign in bugs I cannot reproduce. I've had something similar before on an earlier branch where I needed to refresh. Are there any steps to reproduce on your end @thebeyondr ?

**Pull request merged**
